apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: going-to-go/example
  title: going-to-go/example
  description: |
    Template Project for Go API Backend Server
  annotations:
    github.com/project-slug: ispec-inc/going-to-go/example
    backstage.io/techdocs-ref: github:https://github.com/ispec-inc/going-to-go/example
  tags:
    - recommended
    - golang
    - template
spec:
  type: service
  owner: yamad07
  lifecycle: experimental
