apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: going-to-go
  title: Go Monolith API Base
  description: |
    Template Project for Go API Backend Server
  tags:
    - recommended
    - golang
    - template
spec:
  type: api
  owner: yamad07
  lifecycle: experimental
  templater: cookiecutter
  path: '.'
  schema:
    required:
      - component_id
      - description
      - organization_name
    properties:
      component_id:
        title: Name
        type: string
        description: Unique name of the component
      description:
        title: Description
        type: string
        description: Description of the component
      organization_name:
        title: Organization
        type: string
        description: Organization name of the component
